#server:
#  port: 8085
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: none
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mysql://13.233.198.21:3306/user
    username: root
    password: TS@001002
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers: 13.233.252.31:9092
    consumer:
      group-id: svc_name
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.unittest.user.kafka.serde.JsonSerializer
